import Link from "next/link"
import { HeartPulse } from "lucide-react"
import { AccountMenu } from "@/components/auth/account-menu"
import { MobileNavigationDrawer } from "@/components/mobile-navigation-drawer"
import { NavigationLink } from "@/components/navigation-link"
import { NotificationBell } from "@/components/patient/notification-bell"
import { buttonVariants } from "@/components/ui/button"
import { getAuthState, getDoctorRecord } from "@/lib/auth"
import { getNavigation } from "@/lib/navigation"
import { cn } from "@/lib/utils"
const guestLinks = [{ href: "/doctors", label: "Find a doctor" }, { href: "#services", label: "Services" }, { href: "#about", label: "Why MediBook" }, { href: "#team", label: "Our team" }]
export async function LandingHeader() { const [{ user, profile }, doctor] = await Promise.all([getAuthState(), getDoctorRecord()]); const navigation = getNavigation(profile?.role, doctor?.approval_status); const links = user ? navigation.links : guestLinks; return <header className="sticky top-0 z-40 mx-auto flex min-h-20 max-w-7xl items-center justify-between gap-4 bg-[#E7F7F5]/95 px-5 backdrop-blur sm:px-8"><Link href="/" className="flex shrink-0 items-center gap-2.5 font-bold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-[#0F766E] text-white"><HeartPulse className="size-5" /></span><span>MediBook<span className="block text-[9px] font-medium tracking-[.14em] text-[#0F766E]">YOUR CARE, CLEARLY</span></span></Link><nav aria-label="Primary navigation" className="hidden items-center gap-7 text-sm font-medium text-slate-600 lg:flex">{links.map((link) => <NavigationLink key={link.href} link={link} className="transition hover:text-[#0F766E] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#0F766E]" />)}</nav><div className="flex items-center gap-2">{user ? <><div className="hidden lg:block"><NotificationBell userId={user.id} href={navigation.notificationsHref} /></div><div className="hidden lg:block"><AccountMenu userId={user.id} name={profile?.full_name} email={user.email} role={navigation.accountRole} /></div></> : <><Link href="/login" className={cn(buttonVariants({ variant: "ghost" }), "hidden rounded-xl lg:inline-flex")}>Log in</Link><Link href="/signup" className={cn(buttonVariants(), "hidden rounded-xl bg-[#0F766E] hover:bg-[#0D5F59] lg:inline-flex")}>Get started</Link></>}<MobileNavigationDrawer links={user ? navigation.mobileLinks : guestLinks} userId={user?.id} name={profile?.full_name} email={user?.email} role={user ? navigation.accountRole : undefined} notificationsHref={user ? navigation.notificationsHref : undefined} desktopBreakpoint="lg" headerOffset="20" /></div></header> }
