import { updateAppointmentStatus } from "@/app/admin/actions"
import { createClient } from "@/lib/supabase/server"

const statusClass: Record<string, string> = { pending: "bg-amber-100 text-amber-800", confirmed: "bg-green-100 text-green-800", cancelled: "bg-red-100 text-red-800", completed: "bg-slate-200 text-slate-700" }

export default async function AdminAppointmentsPage() {
  const supabase = await createClient()
  const { data: appointments, error } = await supabase.from("appointments").select("id, appointment_date, start_time, status, reason, doctors(full_name), profiles(full_name, phone)").order("appointment_date", { ascending: false }).order("start_time", { ascending: false })
  return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#0F766E]">Booking management</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Appointments</h1><p className="mt-2 text-slate-600">Confirm, cancel, or mark clinic visits complete.</p>{error ? <p className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-800">We couldn&apos;t load appointments. Please refresh and try again.</p> : appointments?.length ? <div className="mt-8 grid gap-3">{appointments.map((appointment) => { const doctor = appointment.doctors as unknown as { full_name: string } | null; const patient = appointment.profiles as unknown as { full_name: string; phone: string | null } | null; return <article key={appointment.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex sm:items-center sm:justify-between sm:gap-5"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{patient?.full_name ?? "Patient"}</h2><span className={"rounded-full px-2.5 py-1 text-xs font-semibold capitalize " + statusClass[appointment.status]}>{appointment.status}</span></div><p className="mt-2 text-sm text-[#0F766E]">{doctor?.full_name ?? "Clinic doctor"}</p><p className="mt-1 text-sm text-slate-600">{appointment.appointment_date} at {appointment.start_time.slice(0, 5)}{patient?.phone ? " · " + patient.phone : ""}</p>{appointment.reason ? <p className="mt-2 text-sm text-slate-500">Reason: {appointment.reason}</p> : null}</div><form action={updateAppointmentStatus} className="mt-4 flex gap-2 sm:mt-0"><input type="hidden" name="id" value={appointment.id} /><select name="status" defaultValue={appointment.status} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option><option value="completed">Completed</option></select><button className="h-10 rounded-xl bg-[#0F766E] px-4 text-sm font-semibold text-white hover:bg-[#0D5F59]">Update</button></form></article> })}</div> : <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No appointments have been made yet.</div>}</main>
}
