import Image from "next/image"
import Link from "next/link"
import { Suspense } from "react"
import { ArrowRight, BadgeCheck, HeartPulse, Menu, MessageCircleHeart, Search, ShieldCheck } from "lucide-react"

import { SpecialtyCards, SpecialtyCardsLoading } from "@/components/home/specialty-cards"
import { buttonVariants } from "@/components/ui/button"
import { LandingPageEffects } from "@/components/home/landing-page-effects"
import { ServicesShowcase } from "@/components/home/services-showcase"
import { cn } from "@/lib/utils"

const testimonials = [
  { name: "Maya R.", initials: "MR", text: "Booking my follow-up took less than a minute. It felt calm, clear, and genuinely easy." },
  { name: "Daniel K.", initials: "DK", text: "I could see the available times right away and choose a doctor I felt good about." },
]

export default function Home() {
  return (
    <main data-landing-page className="overflow-hidden bg-white text-slate-950">
      <section className="relative bg-[#E7F7F5]">
        <div aria-hidden className="absolute -left-28 top-28 size-80 rounded-full bg-[#B8EEE8]/70 blur-3xl" />
        <div aria-hidden className="absolute right-[8%] top-24 size-64 rounded-full border-[32px] border-white/40" />
        <header className="relative z-10 mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
          <Link href="/" className="flex items-center gap-2.5 font-bold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-[#0F766E] text-white"><HeartPulse className="size-5" /></span><span>MediBook<span className="block text-[9px] font-medium tracking-[.14em] text-[#0F766E]">YOUR CARE, CLEARLY</span></span></Link>
          <nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 lg:flex"><Link href="/doctors" className="transition hover:text-[#0F766E]">Find a doctor</Link><a href="#services" className="transition hover:text-[#0F766E]">Services</a><a href="#about" className="transition hover:text-[#0F766E]">Why MediBook</a><a href="#team" className="transition hover:text-[#0F766E]">Our team</a></nav>
          <div className="flex items-center gap-2"><Link href="/login" className={cn(buttonVariants({ variant: "ghost" }), "hidden rounded-xl sm:inline-flex")}>Log in</Link><Link href="/signup" className={cn(buttonVariants(), "rounded-xl bg-[#0F766E] hover:bg-[#0D5F59]")}>Get started</Link><button aria-label="Open navigation" className="grid size-10 place-items-center rounded-xl border border-teal-800/10 text-[#0F766E] lg:hidden"><Menu className="size-5" /></button></div>
        </header>
        <div className="relative z-[1] mx-auto grid max-w-7xl gap-8 px-5 pb-14 pt-10 sm:px-8 lg:grid-cols-[.88fr_1.12fr] lg:items-center lg:pb-0 lg:pt-14">
          <div className="pb-2 lg:pb-20"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0F766E]">Healthcare made simple</p><h1 className="mt-4 max-w-xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">Exceptional care,<br /><span className="text-[#0F9E96]">every time.</span></h1><p className="mt-6 max-w-md text-base leading-7 text-slate-600">Discover trusted doctors, view live availability, and book your next appointment from one reassuring place.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/doctors" className={cn(buttonVariants({ size: "lg" }), "h-11 rounded-xl bg-[#0F766E] px-5 hover:bg-[#0D5F59]")}>Book an appointment <ArrowRight className="size-4" /></Link><Link href="/doctors" className={cn(buttonVariants({ size: "lg", variant: "outline" }), "h-11 rounded-xl border-teal-900/10 bg-white px-5 hover:bg-white")}><Search className="size-4" /> Find a doctor</Link></div><div className="mt-9 flex items-center gap-3"><div className="flex -space-x-2">{["A", "J", "L", "S"].map((person, index) => <span key={person} className={cn("grid size-8 place-items-center rounded-full border-2 border-[#E7F7F5] text-[10px] font-bold text-white", ["bg-teal-600", "bg-sky-500", "bg-amber-500", "bg-rose-500"][index])}>{person}</span>)}</div><p className="text-sm text-slate-600"><strong className="text-slate-950">12k+</strong> people book with confidence</p></div></div>
          <div className="relative min-h-[380px] sm:min-h-[500px] lg:min-h-[570px]"><div className="absolute bottom-0 left-1/2 h-[91%] w-[min(33rem,91%)] -translate-x-1/2 rounded-t-[11rem] bg-[#10B8AD]" /><Image src="/images/medibook-hero-doctor.png" alt="A caring MediBook doctor" fill priority className="object-cover object-[62%_10%] [clip-path:inset(0_5%_0_5%_round_10rem_10rem_0_0)]" sizes="(max-width: 1024px) 100vw, 55vw" /><div className="motion-float motion-float-late absolute left-0 top-10 hidden w-44 rounded-2xl bg-white p-3 shadow-xl sm:block"><p className="text-[10px] font-bold uppercase tracking-wider text-[#0F766E]">Meet your doctor</p><div className="mt-2 space-y-2">{["Dr. Priya Nair", "Dr. Alex Chen", "Dr. Sofia Patel"].map((name) => <div className="flex items-center gap-2" key={name}><span className="grid size-6 place-items-center rounded-full bg-[#CCFBF1] text-[9px] font-bold text-[#0F766E]">+</span><span className="text-[10px] font-medium">{name}</span></div>)}</div><Link href="/doctors" className="mt-3 inline-flex text-[10px] font-bold text-[#0F766E]">See all doctors <ArrowRight className="size-3" /></Link></div><div className="motion-float motion-float-later absolute bottom-10 right-0 rounded-2xl bg-white p-3 shadow-xl sm:right-1"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-xl bg-[#CCFBF1] text-[#0F766E]"><BadgeCheck className="size-4" /></span><div><p className="text-xs font-bold">Care you can trust</p><p className="text-[10px] text-slate-500">Verified clinicians</p></div></div></div></div>
        </div>
      </section>
      <Suspense fallback={<SpecialtyCardsLoading />}><SpecialtyCards /></Suspense>
      <ServicesShowcase />
      <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8 lg:pb-28"><div className="relative overflow-hidden rounded-3xl bg-[#0F9E96] px-7 py-10 text-white sm:px-12 sm:py-12"><div aria-hidden className="absolute -right-20 -top-20 size-72 rounded-full border-[32px] border-white/10" /><div className="relative grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-teal-100">Care from anywhere</p><h2 className="mt-3 max-w-md text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Talk to a doctor from the comfort of home.</h2><p className="mt-4 max-w-md text-sm leading-6 text-teal-50/85">Book an in-person visit or start with a consultation that works around your schedule.</p><Link href="/doctors" className={cn(buttonVariants({ variant: "secondary" }), "mt-7 rounded-xl bg-white text-[#0F766E] hover:bg-teal-50")}>Find a doctor</Link></div><div className="hidden md:grid size-28 place-items-center rounded-full border border-white/20 bg-white/10"><MessageCircleHeart className="size-12 text-teal-50" /></div></div></div></section>
      <section id="about" className="bg-[#F0FAF9] py-20"><div className="mx-auto grid max-w-6xl gap-10 px-5 sm:px-8 md:grid-cols-[.85fr_1.15fr] md:items-center"><div className="relative mx-auto h-80 w-full max-w-sm overflow-hidden rounded-3xl bg-[#CDEDEA]"><Image src="/images/care-team.png" alt="A trusted healthcare team reviewing a care plan" fill className="object-cover object-[58%_18%]" sizes="(max-width: 768px) 100vw, 35vw" /></div><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0F766E]">Your health, on your terms</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Simple scheduling. More peace of mind.</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">MediBook makes it easier to plan care without phone queues or uncertain availability. Your appointments, doctors, and next steps stay in one secure place.</p><ul className="mt-6 space-y-3">{["Live availability you can count on", "Trusted clinicians and clear appointment details", "Private, secure care management"].map((item) => <li className="flex items-center gap-3 text-sm font-medium text-slate-700" key={item}><ShieldCheck className="size-5 text-[#0F766E]" />{item}</li>)}</ul></div></div></section>
      <section className="bg-[#087D78] py-20 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[.16em] text-teal-100">Stories from MediBook</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">What patients are saying</h2></div><div className="mx-auto mt-10 grid max-w-4xl gap-5 md:grid-cols-2">{testimonials.map((item) => <article className="rounded-2xl bg-white p-6 text-slate-900 shadow-lg" key={item.name}><span className="text-4xl font-serif leading-none text-[#0F9E96]">“</span><p className="mt-2 text-sm leading-6 text-slate-600">{item.text}</p><div className="mt-5 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#CCFBF1] text-xs font-bold text-[#0F766E]">{item.initials}</span><div><p className="text-sm font-bold">{item.name}</p><p className="text-xs text-slate-500">MediBook patient</p></div></div></article>)}</div></div></section>
      <section id="team" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0F766E]">Meet the people behind the care</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">A team ready to listen.</h2></div><Link href="/doctors" className="inline-flex items-center gap-1 text-sm font-bold text-[#0F766E]">View all doctors <ArrowRight className="size-4" /></Link></div><div className="mt-10 grid gap-5 sm:grid-cols-3">{[["Dr. Priya Nair", "/images/medibook-hero-doctor.png", "Family medicine"], ["Dr. Alex Chen", "/images/doctor-alex.png", "Internal medicine"], ["Dr. Sofia Patel", "/images/doctor-sofia.png", "Patient care specialist"]].map(([name, image, specialty]) => <article className="overflow-hidden rounded-2xl bg-[#DDF3F3]" key={name}><div className="relative aspect-[1.15] overflow-hidden"><Image src={image} alt={name} fill className="object-cover object-[50%_10%]" sizes="(max-width: 640px) 100vw, 33vw" /></div><div className="bg-white p-5"><p className="font-semibold">{name}</p><p className="mt-1 text-sm text-[#0F766E]">{specialty}</p></div></article>)}</div></section>
      <footer className="bg-[#073B3A] text-slate-300"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 md:grid-cols-[1.4fr_repeat(3,1fr)]"><div><Link href="/" className="flex items-center gap-2 font-bold text-white"><span className="grid size-8 place-items-center rounded-lg bg-[#0F9E96]"><HeartPulse className="size-4" /></span>MediBook</Link><p className="mt-4 max-w-xs text-sm leading-6 text-teal-100/70">A calmer, clearer way to find and book the care you need.</p></div><div><p className="text-sm font-bold text-white">Explore</p><div className="mt-4 space-y-2 text-sm"><Link className="block hover:text-white" href="/doctors">Find a doctor</Link><a className="block hover:text-white" href="#services">Services</a><Link className="block hover:text-white" href="/appointments">Appointments</Link></div></div><div><p className="text-sm font-bold text-white">Support</p><div className="mt-4 space-y-2 text-sm"><a className="block hover:text-white" href="#about">How it works</a><Link className="block hover:text-white" href="/login">Log in</Link><Link className="block hover:text-white" href="/signup">Create account</Link></div></div><div><p className="text-sm font-bold text-white">Care with confidence</p><p className="mt-4 text-sm leading-6 text-teal-100/70">Your health information is handled with care and privacy.</p></div></div><div className="border-t border-white/10 px-5 py-5 text-center text-xs text-teal-100/55">© {new Date().getFullYear()} MediBook. Care made clearer.</div></footer>
      <LandingPageEffects />
    </main>
  )
}
