import Link from "next/link"

import { createDoctor, toggleDoctor } from "@/app/admin/actions"
import { createClient } from "@/lib/supabase/server"

const field = "h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[#0F766E]"

export default async function AdminDoctorsPage() {
  const supabase = await createClient()
  const [{ data: doctors, error }, { data: specialties }] = await Promise.all([supabase.from("doctors").select("id, full_name, fee, is_active, specialties(name)").order("full_name"), supabase.from("specialties").select("id, name").order("name")])
  return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#0F766E]">Directory management</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Doctors</h1><p className="mt-2 text-slate-600">Add clinicians, manage schedules, and control patient visibility.</p><form action={createDoctor} className="mt-8 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-4"><input name="full_name" required placeholder="Doctor full name" className={field} /><select name="specialty_id" className={field}><option value="">Specialty</option>{specialties?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="fee" type="number" min="0" required placeholder="Fee (Rs.)" className={field} /><button className="h-10 rounded-xl bg-[#0F766E] px-4 text-sm font-semibold text-white hover:bg-[#0D5F59]">Add doctor</button><textarea name="bio" className="min-h-20 rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-[#0F766E] md:col-span-4" placeholder="Short professional bio (optional)" /></form>{error ? <p className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-800">We couldn&apos;t load doctors. Please refresh and try again.</p> : doctors?.length ? <div className="mt-6 grid gap-3">{doctors.map((doctor) => { const specialty = doctor.specialties as unknown as { name: string } | null; return <article key={doctor.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h2 className="font-semibold">{doctor.full_name}</h2><p className="mt-1 text-sm text-slate-500">{specialty?.name ?? "No specialty"} · Rs. {Number(doctor.fee).toLocaleString()}</p><span className={doctor.is_active ? "mt-3 inline-flex rounded-full bg-green-100 px-2.5 py-1 text-xs font-semibold text-green-800" : "mt-3 inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600"}>{doctor.is_active ? "Visible to patients" : "Hidden from patients"}</span></div><div className="flex flex-wrap gap-3"><Link href={"/admin/doctors/" + doctor.id + "/schedule"} className="text-sm font-semibold text-[#0F766E] hover:underline">Manage schedule</Link><form action={toggleDoctor}><input type="hidden" name="id" value={doctor.id} /><input type="hidden" name="is_active" value={String(!doctor.is_active)} /><button className="text-sm font-semibold text-slate-600 hover:text-[#0F766E]">{doctor.is_active ? "Hide doctor" : "Make visible"}</button></form></div></article> })}</div> : <div className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No doctors have been added yet.</div>}</main>
}
