"use client"
import { useState } from "react"
import * as yup from "yup"

const schema = yup.object({ full_name: yup.string().trim().matches(/^[\p{L}][\p{L}\s.'-]*$/u, "Use letters only in the doctor’s full name.").required("Enter the doctor’s full name."), fee: yup.number().typeError("Enter a valid consultation fee.").min(0, "Consultation fee cannot be negative.").required("Enter a consultation fee."), bio: yup.string().max(500, "Bio must be 500 characters or fewer.") })
const field = "h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[#0F766E]"
type Props = { action: (data: FormData) => void; specialties: { id: number; name: string }[]; doctor?: { id: string; full_name: string; specialty_id: number | null; fee: number; bio: string | null }; compact?: boolean }
export function DoctorForm({ action, specialties, doctor, compact }: Props) {
 const [errors,setErrors]=useState<Record<string,string>>({}); const [bio,setBio]=useState(doctor?.bio??"")
 async function submit(event: React.FormEvent<HTMLFormElement>) { const form=event.currentTarget; const values=Object.fromEntries(new FormData(form)); try { await schema.validate(values,{abortEarly:false}); setErrors({}) } catch(error) { event.preventDefault(); if(error instanceof yup.ValidationError) setErrors(Object.fromEntries(error.inner.map(i=>[i.path??"form",i.message]))) } }
 const clear=(key:string)=>setErrors(e=>({...e,[key]:""}))
 return <form action={action} onSubmit={submit} className={compact ? "mt-8 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-4" : "mt-8 grid gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"}>{doctor?<input type="hidden" name="id" value={doctor.id}/>:null}<label className="grid gap-2 text-sm font-medium">Full name<input name="full_name" defaultValue={doctor?.full_name} onChange={()=>clear("full_name")} aria-invalid={Boolean(errors.full_name)} aria-describedby={errors.full_name?"doctor-name-error":undefined} className={field}/>{errors.full_name?<span id="doctor-name-error" className="text-sm text-red-600">{errors.full_name}</span>:null}</label><label className="grid gap-2 text-sm font-medium">Specialty<select name="specialty_id" defaultValue={doctor?.specialty_id??""} className={field}><option value="">No specialty</option>{specialties.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Consultation fee (Rs.)<input name="fee" type="number" min="0" defaultValue={doctor?.fee} onChange={()=>clear("fee")} aria-invalid={Boolean(errors.fee)} aria-describedby={errors.fee?"doctor-fee-error":undefined} className={field}/>{errors.fee?<span id="doctor-fee-error" className="text-sm text-red-600">{errors.fee}</span>:null}</label>{compact?<button className="h-10 rounded-xl bg-[#0F766E] px-4 text-sm font-semibold text-white hover:bg-[#0D5F59]">Add doctor</button>:null}<label className={compact?"grid gap-2 text-sm font-medium md:col-span-4":"grid gap-2 text-sm font-medium"}>Bio <span className="font-normal text-slate-500">{500-bio.length} characters remaining</span><textarea name="bio" value={bio} onChange={e=>{setBio(e.target.value);clear("bio")}} maxLength={500} aria-invalid={Boolean(errors.bio)} aria-describedby={errors.bio?"doctor-bio-error":undefined} className="min-h-24 rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-[#0F766E]"/>{errors.bio?<span id="doctor-bio-error" className="text-sm text-red-600">{errors.bio}</span>:null}</label>{!compact?<button className="h-10 rounded-xl bg-[#0F766E] px-4 text-sm font-semibold text-white hover:bg-[#0D5F59]">Save doctor</button>:null}</form>
}
